// product
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_CHANGE = 'PRODUCT_CHANGE';
export const PRODUCT_SELECT = 'PRODUCT_SELECT';
export const PRODUCT_CANCEL_SELECT = 'PRODUCT_CANCEL_SELECT';

//backlog
export const BACKLOG_LIST_SUCCESS = 'BACKLOG_LIST_SUCCESS';
export const BACKLOG_CHANGE = 'BACKLOG_CHANGE';

//sprint
export const SPRINT_LIST_SUCCESS = 'SPRINT_LIST_SUCCESS';
export const SPRINT_CHANGE = 'SPRINT_CHANGE';

//user
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_CHANGE = 'USER_CHANGE';

//user info
export const USERINFO_CHANGE = 'USERINFO_CHANGE';

//sprint backlog
export const SPRINTBACKLOG_LIST_SUCCESS = "SPRINTBACKLOG_LIST_SUCCESS";
export const SPRINTBACKLOG_CHANGE = "SPRINTBACKLOG_CHANGE";
export const SPRINTBACKLOG_TODO_LIST_SUCCESS = "SPRINTBACKLOG_TODO_LIST_SUCCESS";
export const SPRINTBACKLOG_DOING_LIST_SUCCESS = "SPRINTBACKLOG_DOING_LIST_SUCCESS";
export const SPRINTBACKLOG_DONE_LIST_SUCCESS = "SPRINTBACKLOG_DONE_LIST_SUCCESS";
export const SPRINTBACKLOG_ALL_LIST_SUCCESS = "SPRINTBACKLOG_ALL_LIST_SUCCESS";

//progress
export const PROGRESS_CHANGE = "PROGRESS_CHANGE";

//enterprise
export const ENTERPRISE_LIST_SUCCESS = 'ENTERPRISE_LIST_SUCCESS';
export const ENTERPRISE_CHANGE = 'ENTERPRISE_CHANGE';